--Database objects---
CREATE TABLE T_USER 
   (	USER_ID NUMBER NOT NULL ENABLE, 
	USER_NAME VARCHAR2(20 BYTE), 
	USER_PASSWORD VARCHAR2(20 BYTE), 
	USER_ROLE VARCHAR2(20 BYTE), 
	 CONSTRAINT T_USER_PK PRIMARY KEY (USER_ID)
   );
   
CREATE TABLE T_PETDETAILS 
   (	PET_ID NUMBER NOT NULL ENABLE, 
	CATEGORY_ID NUMBER, 
	PET_NAME VARCHAR2(50 BYTE), 
	TAG_ID NUMBER, 
	PET_STATUS VARCHAR2(20 BYTE), 
	PHOTOURLS VARCHAR2(500 BYTE), 
	 CONSTRAINT PETDETAILS_PK PRIMARY KEY (PET_ID), 
	 CONSTRAINT CATEGORY_FK FOREIGN KEY (CATEGORY_ID)
	  REFERENCES SYSTEM.T_PETCATEGORY (CATEGORY_ID) ENABLE, 
	 CONSTRAINT TAG_FK FOREIGN KEY (TAG_ID)
	  REFERENCES SYSTEM.T_TAGDETAILS (TAG_ID) ENABLE
   );
   
CREATE TABLE T_PETCATEGORY 
   (	CATEGORY_ID NUMBER NOT NULL ENABLE, 
	CATEGORY_NAME VARCHAR2(20 BYTE), 
	 CONSTRAINT T_PETCATEGORY_PK PRIMARY KEY (CATEGORY_ID)
   );
   
CREATE TABLE T_TAGDETAILS 
   (	TAG_ID NUMBER NOT NULL ENABLE, 
	TAG_NAME VARCHAR2(20 BYTE), 
	 CONSTRAINT T_TAGDETAILS_PK PRIMARY KEY (TAG_ID)
   );
   
   
--Day 0 Setup ---  
Insert into T_PETCATEGORY (CATEGORY_ID,CATEGORY_NAME) values (1,'Dog');
Insert into T_PETCATEGORY (CATEGORY_ID,CATEGORY_NAME) values (2,'Cat');
Insert into T_TAGDETAILS (TAG_ID,TAG_NAME) values (1,'Tag1');
Insert into T_TAGDETAILS (TAG_ID,TAG_NAME) values (2,'Tag2')